AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Application for sending Withings Weight data to Garmin Connect.'

Resources:
  WithingsOAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: WithingsOAuthSecret
      Description: 'Withings OAuth Credentials'
      SecretString: 'REPLACE THROUGH SCRIPT'
  GarminOAuth1Secret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: GarminOAuth1Secret
      Description: 'Garmin OAuth1 Credentials'
      SecretString: 'REPLACE THROUGH SCRIPT'
  GarminOAuth2Secret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: GarminOAuth2Secret
      Description: 'Garmin OAuth2 Credentials'
      SecretString: 'REPLACE THROUGH SCRIPT'

  SyncFunction:
    Type: AWS::Serverless::Function
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/lambda/index.ts
    Properties:
      Runtime: nodejs20.x
      Handler: src/lambda/index.handler
      CodeUri: .
      MemorySize: 1024
      Timeout: 10
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:UpdateSecret
              Resource:
                - !Sub '${WithingsOAuthSecret}'
                - !Sub '${GarminOAuth1Secret}'
                - !Sub '${GarminOAuth2Secret}'
